# Base de donn√©es uniquement : pour lancer l'API et le front en local (sans Docker pour l'app).
# Usage: docker compose -f infra/docker/compose.dev-db-only.yml up -d
# Puis: lancer l'API (uvicorn) et le front (npm run dev) sur la machine.
volumes:
  madavola_db:

services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madavola
    ports:
      - "5432:5432"
    volumes:
      - madavola_db:/var/lib/postgresql/data
